# Generated by Django 5.2.5 on 2025-08-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='DemandLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistBtoD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.block')),
                ('demand_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.demandlocation')),
            ],
            options={
                'indexes': [models.Index(fields=['demand_location', 'block'], name='myapp_distb_demand__3c95bd_idx'), models.Index(fields=['distance'], name='myapp_distb_distanc_08bb60_idx')],
                'unique_together': {('demand_location', 'block')},
            },
        ),
        migrations.CreateModel(
            name='DistBtoP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in kilometers/miles')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.block')),
                ('power_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.powerplant')),
            ],
            options={
                'indexes': [models.Index(fields=['power_plant', 'block'], name='myapp_distb_power_p_a1c4db_idx'), models.Index(fields=['distance'], name='myapp_distb_distanc_fa1649_idx')],
                'unique_together': {('power_plant', 'block')},
            },
        ),
    ]
