# Generated by Django 5.2.5 on 2025-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_block_land_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
