# Generated by Django 5.2.5 on 2025-08-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_block_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('land_price', models.FloatField(default=None)),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='distbtop',
            name='distance',
            field=models.FloatField(help_text='Distance in kilometers'),
        ),
        migrations.CreateModel(
            name='DistBtoDTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.blocktable')),
                ('demand_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.demandlocation')),
            ],
            options={
                'indexes': [models.Index(fields=['demand_location', 'block'], name='myapp_distb_demand__10ae87_idx'), models.Index(fields=['distance'], name='myapp_distb_distanc_d456ae_idx')],
                'unique_together': {('demand_location', 'block')},
            },
        ),
        migrations.CreateModel(
            name='DistBtoPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.blocktable')),
                ('power_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.powerplant')),
            ],
            options={
                'indexes': [models.Index(fields=['power_plant', 'block'], name='myapp_distb_power_p_7c4958_idx'), models.Index(fields=['distance'], name='myapp_distb_distanc_22cd8d_idx')],
                'unique_together': {('power_plant', 'block')},
            },
        ),
    ]
