# Generated by Django 5.2.5 on 2025-08-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blocktable_alter_distbtop_distance_distbtodtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='distance_demand',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='distance_plants',
            field=models.FloatField(default=0),
        ),
    ]
