# Generated by Django 5.2.5 on 2025-08-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_block_distance_demand_block_distance_plants'),
    ]

    operations = [


        migrations.AlterUniqueTogether(
            name='distbtod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='distbtod',
            name='demand_location',
        ),
        migrations.AlterUniqueTogether(
            name='distbtop',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='distbtop',
            name='power_plant',
        ),
        migrations.AddField(
            model_name='blocktable',
            name='distance_demand',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='blocktable',
            name='distance_plants',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='DistBtoD',
        ),
        migrations.DeleteModel(
            name='DistBtoP',
        ),
    ]
